# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-sicilian-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.6.1
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  # TODO nf-core: Add required software dependencies here
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.7
  - conda-forge::argparse=1.4.0
  - conda-forge::numpy=1.19.2
  - conda-forge::pandas=1.1.3
  - conda-forge::pyarrow=2.0.0
  - bioconda::pysam=0.16.0.1
  - bioconda::umi_tools=1.1.1
